### ISSUE TITLE
The package doesn't work with django 4.0.*

### ISSUE THREAD

**Issue by haddaa** [Tivix/django-rest-auth#661]
when trying to install the recent version of `django-rest-auth `with Django 4 since it uses the deprecated function `ugettext_lazy` from `django.utils.translation` the error :
```
  File "/path/to/views/views.py", line 8, in <module>
    from rest_auth.registration.serializers import SocialLoginSerializer
  File "/path/to/python3.8/site-packages/rest_auth/registration/serializers.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/path/to/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py)
```

**Comment by Omaraitbenhaddi** [comment]
I modified it to fit Django 4.0 while waiting pull request you can use this fork https://github.com/Omaraitbenhaddi/django-rest-auth
